### ISSUE TITLE
hi,bro,Lumberjack and mining change to use scroll  ？

### ISSUE THREAD

**Issue by kevinchow9527** [gdavis/uo-razor-scripts#1]
Lumberjack.razor
mining.razor
 if skill 'magery' >= 60
        overhead 'Time to leave!' 34
        sysmsg 'Lumberjack -> Recall to Inn!' 44
        @setvar! isActive 0
        script 'RecallInn'
    endif

**Comment by gdavis** [comment]
Hey @kevinchow9527, you can feel free to open a pull request if you have working changes you'd like to add
